import "./globals.css";
import { Providers } from "@/app/providers";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          {children}
        </Providers>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
